### PR TITLE
Update Chart.yaml

### PR DESCRIPTION
**Pull request by ankh-daemon**
bump version

### CODE REVIEW

**Comment by ankh-daemon** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ankh-daemon**
You can assign the PR to them by writing `/assign @ankh-daemon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ankh-is%2Fhelm-charts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ankh-is/helm-charts/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ankh-daemon** [comment]
@ankh-daemon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | ad9acc37481c6a488a38c5ed68a14b2343cd2ddd | [link](http://dashboard-jx.192.168.64.9.nip.io/namespaces/jx/pipelineruns/pr-z5xbb) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ankh-daemon** [comment]
@ankh-daemon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 791ac083b83e230496218f9ec0164d48876d7d18 | [link](http://dashboard-jx.192.168.64.9.nip.io/namespaces/jx/pipelineruns/pr-rxgzx) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ankh-daemon** [comment]
@ankh-daemon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr | 0d9de5dbd49e8568b98f2aa26f20cebd168f361d | [link](http://dashboard-jx.192.168.64.9.nip.io/namespaces/jx/pipelineruns/pr-pm4nq) | `/test pr`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by iamjohnnym — APPROVED** [review]

**Comment by ankh-daemon** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[iamjohnnym](https://github.com/ankh-is/helm-charts/pull/1#issuecomment-793299332 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ankh-daemon**
You can assign the PR to them by writing `/assign @ankh-daemon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ankh-is%2Fhelm-charts).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ankh-is/helm-charts/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
